### PR TITLE
Draw ideographic space as special characters.

### PR DESCRIPTION
**Pull request by m-matsubara**
I know this is probably only in Japan, but it uses a whitespace character (U+3000) called Ideographic space. I would like to display this as a whitespace character, separate from U+0020.

' ' -- Space (U+0020)
'　' -- Ideographic space (U+3000)

image

### CODE REVIEW

**Comment by pyscripter** [comment]
It will take some convincing to merge this.

There are many [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character) and I don't want to end up rendering each one of them differently.  

For instance #$A0 is rendered the same as #$20.  Should we render it differently?

How important is it to render the different spaces differently?  And in any case, with the ideographic space you can tell the difference by the width.

image

And if needed you can easily add some functionality to decorate ideographic spaces using [indicators](https://github.com/TurboPack/SynEdit/discussions/160).

**Comment by m-matsubara** [comment]
There are many white space characters, but Japanese people especially use U+0020 and U+3000. It is normal to use U+3000 in ordinary texts, but sometimes people make the mistake of using U+3000 in source code when they should have used U+0020. Compilers often do not treat U+3000 as a whitespace character, so this creates an invisible syntax error and confuses programmers.
In order to quickly notice this, it would be beneficial for the Japanese to make it easy to distinguish between U+0020 and U+3000.

This modification probably only benefits Japanese people. If it is determined that there is little overall benefit, there is no need to merge.

**Comment by pyscripter** [comment]
One idea is to draw **all** non-standard spaces differently, by decorating the space glyph.  e.g.

This is by underline:
image

This is bold

image

bold mixed

image


What do you think?

**Comment by m-matsubara** [comment]
thank you.
I thought the underlined ideas were good.
Does this mean that not only ideographic space but also non-ASCII spaces are underlined (or bold)?
If you think about it, non-ASCII spaces can get mixed into source code and cause syntax errors even outside of Japan. (This is especially common in Japan due to the frequency of use of Ideographic spaces.)

**Comment by pyscripter** [comment]
Commited the underline solution in https://github.com/pyscripter/SynEdit/commit/565c9c39406ff030dae5249ec4430453e765997b.

All whitespace characters <> #32 are shown underlined.

**Pull request closed without merging**
