### PR TITLE
Improved styling and performance of completion proposal.

### PR DESCRIPTION
**Pull request by vincentparrett**
Reduces flicker and scrolling performance of the completion propsal window, also improves styling a bit.

### CODE REVIEW

**Comment by pyscripter** [comment]
Thanks!  I think you are solving the following issues:

- Flicker reduction
- Appearance 
  - Getting rid of the thick border while keeping the form resizable
  - Displaying a grip when the form is resizable.
- Per monitor DPI awareness

Am I right?   

I will have a closer look and get back to you.   One thing I am not sure I like, is the fact that the grip takes space at the bottom of the form, which could otherwise be used to show an extra row.  Also, Microsoft is moving away from showing grips in resizable forms.  Just look at the File Explorer or Word for instance in Windows 11.  VS Code code completion is resizable, but without a grip. Maybe the grip can become optional.

**Comment by vincentparrett** [comment]
Happy to make the gripper optional. I was thinking of adding an option to show a message in the gripper bar (like vs does). 

It's a while now since I did this so will have to revisit the code to remember exactly what I did!

**Comment by pyscripter** [comment]
> I was thinking of adding an option to show a message in the gripper bar (like vs does).

That would make the gripper space worthwhile.  But, I cannot think of any useful message in typical code completion. In PyScripter I show info related to the selected value in a separate Hint Window:
image

On a second thought, maybe one could show there the current filter.  

Let me dig a bit deeper in what you have done first, before you make any further changes.

**Comment by pyscripter** [comment]
I finally got some time to look deeper in your PR.   I will merge it manually and I have already merged quite a bit of it (the refactoring of the paint method, the CreateParams and more).

Here is where I stand:
[SynCompletionProposal.zip](https://github.com/pyscripter/SynEdit/files/10197956/SynCompletionProposal.zip)
I still have to add the Grip stuff and I am now looking at DPI-awareness.
I am using the Completion Proposal Demo from the repo to test.

In the meantime, I have some questions:
- Your added/changed mouse routines aimed at making the form resizable.  But this was already taken care of, by handling WM_NCHITTEST.  I can resize the form without these mouse routines (MouseDown, MouseUp, MouseMove).  Are they really needed?  You can test with the provided code.  I could adapt WMNCHitTest to allow resizing only from the bottom right and take account of the grip size.
- I have changed CreateParams to include WS_BORDER.   In the past CreateParams added a shadow (CS_DROPSHADOW).  I noticed you removed it.  If that was on purpose (you don't like the shadow), we could add a property say PaintFormShadow to control this.
- Flicker:  I have replaced WMEraseBackground with the csOpaque control style.  With csOpaque  WMEraseBackground was never called.   I have noticed that you set DoubleBuffered to True and replaced a couple of Invalidate calls with direct calls to PaintICodeItems.  Whilst, this restricts the area that is repainted when the form has a titile and a grip, Invalidate has the advantage that when you are scrolling fast, you repaint fewer times.    Could you please do some testing and confirm that both changes reduce flicker?

**Comment by pyscripter** [comment]
@vincentparrett 
Commit https://github.com/pyscripter/SynEdit/commit/6bdd016073ecf22ad8cebf437349bed92040e276.  I think I got everything in.  Thanks again for the PR!

New properties: 
- PaintFormShadow (default True)
- ShowGripper (default False)

The defaults emulate current looks.

Other points:
- Further cleanup and simplifications.
- Should now be per monitor DPI aware.   Please test, since I followed a quite different method than yours.

The only thing left out is in relation to flicker.   I have not set DoubleBuffered to True (it can be done programmatically anyway),  and I have kept the two calls to Invalidate (see above).   I see no flicker here, but if you find that either of the above have positive impact I would be happy to accept a new PR.

Also it would be good to be able to display a string in the gripper bar.   If you find the time, please submit a PR to that effect.

**Comment by pyscripter** [comment]
@vincentparrett Any feedback?

**Comment by vincentparrett** [comment]
Sorry not yet, will try to get to it next week.. seriously snowed under with other stuff at the moment.

**Comment by vincentparrett** [comment]
But just reading your comment about WS_BORDER - that was one of the things I intentially removed - I really dislike the fat border that looks like windows 95.

**Comment by pyscripter** [comment]
Now it is as in your PR.  Shadow is optional.

**Comment by vincentparrett** [comment]
Looks pretty good, however line hight does not appear to be scaling - this is 140dpi

image

**Comment by vincentparrett** [comment]
This is on 96 dpi screen
image

**Comment by pyscripter** [comment]
Looks like fonts do scale well.
I will have a look.  What is the monitor setup?
Primary secondary?
Design DPI?

**Comment by vincentparrett** [comment]
96 dpi is 2650*1440 (primary), 140dpi is 3840*2160 (secondary)

**Comment by vincentparrett** [comment]
desing dpi is 96 (always, due to the cluster... that is 11.x high dpi support)

**Comment by pyscripter** [comment]
Strange.  I have tested with an identical setup here and looked fine.

Are you doing any font scaling in your program?  For example are you assigning a font which may be scaled to the Code completion font?  If you are you should set the the FontsAreScaled to true, so that no further scaling takes place.


Could you try with Completion demo and see whether you have the same problem?

**Comment by vincentparrett** [comment]
The demo looks fine, however it doesn't use images - and it's the images that are overflowing the line height. The images are 16x16 by default, but done with a virtualimagelist/imagecollection. I guess the item height needs to take the image height into consideration.

**Comment by pyscripter** [comment]
Are you doing any font scaling in your program? For example are you assigning a font which may be scaled to the Code completion font? If you are you should set the the FontsAreScaled to true, so that no further scaling takes place.

Images should be taken care of by using a VirtualImageList.  Or else you would have to manually scale the ImageList.

At the top of RecalcFormPlacement I am calling ScaleForPPI.  This should scale the images to the correct PPI assuming you are using a VirtualImageList.  It should also prevent any further scaling. All measurement and scaling happens in RecalcFormPlacement.  

I am not sure why but it appears that both Images and Fonts are doubly scaled. Any clues?

**Comment by vincentparrett** [comment]
Not sure what is going on. I had set the fonts at design time (to consolas) and after reverting to the defaults it looks worse. 

image

I will try to look at this more tomorrow - have to head out with family now.

**Comment by pyscripter** [comment]
Good.  Enjoy family time....

I am very keen to resolve this.  So let's continue tomorrow.

I take it that the VirtualImageList is in the same form containing the SynEdit.
One thing you can do is put a breakpoint at TVirtualImageList.DPIChangedMessageHandler and check why it double scales.
It appears that the completion form is scaled again after RecalcFormPlacement is called.  Hence the wrong FEffectiveItemHeight.

I have added an ImageCollection/VirtualImageList to the demo and it scales correctly as I move the form between monitors.

**Comment by pyscripter** [comment]
I updated the demo to include images.   It still scales OK here.

**Comment by vincentparrett** [comment]
The problem is when the ItemHeight property is set at design time. The issue is that FItemHeight needs to be scaled - which I had done in my PR

```delphi
procedure TSynBaseCompletionProposalForm.RecalcItemHeight;
begin
  Canvas.Font.Assign(FFont);
  FFontHeight := Canvas.TextHeight(TextHeightString);
  if FItemHeight > 0 then
    FEffectiveItemHeight := FItemHeight <<<<<<<<
  else
    FEffectiveItemHeight := FFontHeight;
end;
````

If I add back in the change in my PR to scale the itemheight

````delphi
  if FItemHeight > 0 then
    FEffectiveItemHeight := MulDiv(FItemHeight, CurrentPPI, 96)
  else
    FEffectiveItemHeight := FFontHeight;
````

Then it behaves as it should.

**Comment by vincentparrett** [comment]
BTW, in the demo, try setting the ItemHeight to 26 and you will see the issue.

**Comment by pyscripter** [comment]
FIxed.  Thanks.  Please check.

**Comment by pyscripter** [comment]
Out of curiosity, how did this affected the image and font sizes?

Oh I see.  Font and Image size were correct.   They just look big because of the PPI.  It was the Item height that was wrong.

**Comment by pyscripter** [comment]
Repeat here as a reminder:

>In relation to flicker. I have not set DoubleBuffered to True (it can be done programmatically anyway), and I have kept the two calls to Invalidate (see above). I see no flicker here, but if you find that either of the above have positive impact I would be happy to accept a new PR.

In general, I do think invalidating is less flickery than immediate redrawing.

>Also it would be good to be able to display a string in the gripper bar. If you find the time, please submit a PR to that effect.

**Comment by vincentparrett** [comment]
Yep, all good thx.

**Comment by vincentparrett** [comment]
Yeah the itemheight made everything else look larger than it should be.

> In general, I do think invalidating is less flickery than immediate redrawing.

I'm not seeing any difference now.. but when I was working on this I found painting only what was needed more effective. The whole design of this completion component/form is horrible - wish I had the time to create a new one from scratch.

**Comment by vincentparrett** [comment]
>Also it would be good to be able to display a string in the gripper bar. If you find the time, please submit a PR to that effect.
Need to think on that for a bit. Adding a simple prop for it would work, but wondering if we could make it more useful somehow.

**Comment by pyscripter** [comment]
> The whole design of this completion component/form is horrible - wish I had the time to create a new one from scratch.

Well this is what happens when you work with code that is 20+ years old.   However, your refactoring helped and I have simplified the logic quite a bit further.

On the positive side, the component is flexible, styled and per-monitor DPI aware.

**Comment by pyscripter** [comment]
> wondering if we could make it more useful somehow

Open to suggestions.  A property would be good anyway.

**Pull request closed without merging**
